### ISSUE TITLE
Log format option

### ISSUE THREAD

**Issue by gjabell** [EdJoPaTo/mqttui#163]
Thank you for `mqttui`, I've been using it for a while now and it just blows away all the other clients I've used in the past!

One feature which I would like to see is a way to specify the output format for the `log` subcommand, particularly a way to log out `json` so it can be processed further by e.g. `jq` in a nice way.

I can make a PR if this is something which other people would like to have as well.

**Comment by EdJoPaTo** [comment]
Thank you for the praise! It's awesome to hear my tool being useful!

I'm not sure how to do JSON output with the log command well. It would create its own line with its own JSON, so there are a bunch of lines following each other each with their separate JSON.

Is `jq` useful for handling a stream of incoming JSON lines? Can this be actually useful? Currently, there is no way to stop `mqttui log` so I'm not sure how well pipes are working with that.

A custom format for log could be neat. Currently, the shown things have a custom width to allow for a somewhat tabular view. Not sure how to do that well with a custom format. Maybe predefine the fields and their widths and the format only specifies which fields are used in what order?

**Comment by EdJoPaTo** [comment]
> I can make a PR

If you want to we can work together on an implementation for that. ()
Personally I would create a struct and use (pseudo) `serde_json::to_non_pretty_string` instead of using `serde_json::json!`. For a CLI flag `log --json` is probably fine?

When the payload is MessagePack or JSON it should probably be structured data and not a string. That would be more helpful for continued usage of the data. I guess payload needs to implement `serde::Serialize` for that? Not sure which [enum representation](https://serde.rs/enum-representations.html) would be the most useful for usage then. Maybe untagged to ignore whether its JSON or MessagePack? :thinking:
