### ISSUE TITLE
Improve broker connection settings

### ISSUE THREAD

**Issue by TotalKrill** [EdJoPaTo/mqttui#70]
Using the broker URL only, makes utilizing the Environment variables for connections more cumbersome to use. 

The project should at least provide a full MQTT url example and if possible provide both the url and the separate fields for connection, where duplication of fields should be prohibited

**Comment by EdJoPaTo** [comment]
Personally I prefer one way of doing things to keep the complexity low. Bot the code and the users will use one single way and bugs are found faster this way.

> Using the broker URL only, makes utilizing the Environment variables for connections more cumbersome to use.

For me it seems like the opposite but maybe I miss something here?
I think its easier to specify one environment variable for the entire broker setting rather than multiple ones when switching to a different broker.

```bash
export MQTTUI_BROKER='mqtt://localhost/'
export MQTTUI_BROKER='mqtts://different-one:666/'
export MQTTUI_BROKER='ws://yet-another/mqtt'
```

versus

```bash
export MQTTUI_BROKER='localhost'

export MQTTUI_BROKER='different-one'
export MQTTUI_PORT=666
export MQTTUI_ENCRYPTION=true

# Websockets would be closest to this
export MQTTUI_BROKER='ws://yet-another/mqtt'
```

When you have a default one specified in your `.bashrc` or wherever, you always need to override / unset these too. This makes it even harder to use default settings like the port for example.

```bash
export MQTTUI_BROKER='simple-host'
unset MQTTUI_PORT
unset MQTTUI_ENCRYPTION
unset MQTTUI_USERNAME
unset MQTTUI_PASSWORD
```

Also see this regarding the WebSockets: https://github.com/bytebeamio/rumqtt/issues/434

Personally I think the URL is both the most powerful way of specifying multiple things and the cleanest one when switching between multiple brokers.

**Comment by EdJoPaTo** [comment]
> It might be nice to have an option to specify the username, password, and client id (mainly the client id) via more command line switches. The ws protocol actually makes a HTTP request first, so manging that URL is a little confusing.
> – @YarekTyshchenko

As the `client_id` is part of the query currently and the same url is used to connect to the HTTP/WS it might be confusing to the Host.
Maybe the query options should still be command line arguments rather than URL query options.

For username/password on the other hand I think its quite good to use them inside the URL.
My question there is: Is the user auth handled inside the websocket or before the websocket connection is built? Is it an MQTT auth inside the WebSocket connection or is that auth process already done on the HTTP server?

**Comment by TotalKrill** [comment]
Well, in my case, the passwords, and client-ids are dynamically changed for connections to our broker ( we use an ACL plugin that requires signed permissions sent to the broker via passwords over an encrypted line, that also configures which topics the client is allowed to access, for how long and with what permissions ) 

I do not see the danger of having both options available, and the code complexity is not significantly increased IMO

**Comment by EdJoPaTo** [comment]
Thanks to the input of @TotalKrill and @YarekTyshchenko I decided against using arguments from a broker URL as they mixup with the WebSocket connection URL. The only change from the last version is the required `mqtt://` prefix now and the gone `--port`. See c41c486

I am curious for other requirements on these arguments before I want to release them in a new version.

**Comment by TotalKrill** [comment]
Seems good to me!

**Comment by EdJoPaTo** [comment]
As the current arguments seem to be fine I am closing this issue. Feel free to mention other areas of improvements when something comes up. Thank you for your input @TotalKrill and @YarekTyshchenko :sparkles:
